apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: free5gc-operator
  template:
    metadata:
      labels:
        name: free5gc-operator
    spec:
      serviceAccountName: free5gc-operator
      containers:
        - name: free5gc-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - free5gc-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "free5gc-operator"
