apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-configmap
data:
  nssfcfg.conf: |
    info:
      version: 1.0.0
      description: NSSF initial local configuration
    
    configuration:
      nssfName: NSSF
      sbi:
        scheme: https
        ipv4Addr: {{ .Values.http.addr }}
        port: 29531
      serviceNameList:
        - nnssf-nsselection
        - nnssf-nssaiavailability
      nrfUri: https://{{ .Values.global.nrf.addr }}:29510
      supportedPlmnList:
        - mcc: 208
          mnc: 93
      supportedNssaiInPlmnList:
        - plmnId:
            mcc: 208
            mnc: 93
          supportedSnssaiList: []
      nsiList: []
      taList:
        - tai:
            plmnId:
              mcc: 208
              mnc: 93
            tac: 1
          accessType: 3GPP_ACCESS
          supportedSnssaiList: []
