apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amf.fullname" . }}
  labels:
    {{- include "amf.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-5"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "amf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "amf.selectorLabels" . | nindent 8 }}
      annotations:
        cni.projectcalico.org/ipAddrs: "[\"{{ .Values.http.addr }}\"]"
        k8s.v1.cni.cncf.io/networks: amf-bridge-net
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "amf.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash"]
          args: ["-c", "./bin/amf"]
          volumeMounts:
            - name: free5gc-config
              mountPath: /root/gofree5gc/config/free5GC.conf
              subPath: free5GC.conf
            - name: amf-config
              mountPath: /root/gofree5gc/config/amfcfg.conf
              subPath: amfcfg.conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: free5gc-config
          configMap:
            name: free5gc-configmap
        - name: amf-config
          configMap:
            name: amf-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
